dist: trusty
sudo: false

language: node_js
node_js:
  - "12"

branches:
  only:
    - main

cache:
  directories:
    - ./node_modules

install:
  - npm install

jobs:
  include:
    - stage: build
      script: npm run build:lib
    - stage: test
      script: npm run lint
    - stage: publish
      if: branch = main AND type = push AND fork = false
      script: npm run publish:lib
