dist: trusty
os: linux
language: node_js

node_js:
  - "12"

cache:
  directories:
    - ./node_modules

install:
  - npm install

jobs:
  include:
    - stage: build
      script: npm run build:lib
    - stage: test
      script: npm run lint
