os:
  - linux
language: node_js
node_js:
  - 8
  - 10
  - 12
script:
  - npm run release
deploy:
  - provider: npm
    edge: true
    email: $NPM_EMAIL
    api_token: $NPM_API_TOKEN
    on:
      tags: true
      node_js: 12
